###GET /todos -should fetch all objects 
GET http://localhost:8081/todos
Content-Type: application/json

###GET /todos/:id -gets a specific object 
GET http://localhost:8081/todos/1
Content-Type: application/json

###POST /todos -adds a new object 
POST http://localhost:8081/todos
Content-Type: application/json

{
  "_id" : 4,
  "task": "Noobie",
  "checked": true
}

###PATCH /todos/:id -updates an existing object 
PATCH http://localhost:8081/todos/1
Content-Type: application/json

{
 "checked": true
}

###PATCH /todos/:id -update check
PATCH http://localhost:8081/todos/1
Content-Type: application/json

{
 "checked": ""
}

###DELETE /todos/:id delete an object 
DELETE  http://localhost:8081/todos/1
Content-Type: application/json

###DELETE /todos
DELETE  http://localhost:8081/todos
Content-Type: application/json
